version: "3"
services:
  mongodb:
    image: mongo:latest
    ports:
      - ${DB_EXTERNAL_PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
    volumes:
      - "./mongo-data:/data/db"
